version: '3.3'
services:
    transmission-openvpn:
        cap_add:
            - NET_ADMIN
        volumes:
            - '/path/to/data/:/data'
            - '/path/to/data/:/config'
        environment:
            - OPENVPN_PROVIDER=nordvpn
            - OPENVPN_CONFIG=Switzerland
            - NORDVPN_CATEGORY=legacy_p2p
            - NORDVPN_PROTOCOL=tcp
            - OPENVPN_USERNAME=YourUser
            - OPENVPN_PASSWORD=YourPassword
            - LOCAL_NETWORK=192.168.0.0/16
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - '9091:9091'
        image: haugene/transmission-openvpn
#docker compose up :)
 # proxy:
 #  image: haugene/transmission-openvpn-proxy
 #  links:
 #    - transmission
 #  ports:
 #    - 8080:8080
 #  volumes:
 #    - /etc/localtime:/etc/localtime:ro

 # rss:
 #  image: haugene/transmission-rss
 #  links:
 #    - transmission
 #  environment:
 #    - RSS_URL=http://.../xxxxx.rss
